import { useCallback, useEffect, useRef } from "react";
import type { MutableRefObject } from "react";
import type { ConversationItem, DebugEntry, ThreadSummary } from "@/types";
import { generateRunMetadata } from "@services/tauri";
import { clampThreadName, looksAutoGeneratedThreadName } from "@threads/utils/threadNaming";
import { asString } from "@threads/utils/threadNormalize";
import {
  getParentThreadIdFromThread,
  getSubagentTaskTitleFromThread,
} from "@threads/utils/threadRpc";

const MAX_PROMPT_CHARS = 1200;
const MAX_SUBAGENT_TITLE_ATTEMPTS = 2;
const SUBAGENT_TITLE_RETRY_DELAY_MS = 1000;

type SubagentTitleLanguage = "zh" | "en" | "mixed";

type SubagentTitleCandidate = {
  key: string;
  workspaceId: string;
  threadId: string;
  parentThreadId: string;
  taskTitle: string;
};

function getFormalThreadTitle(thread: Record<string, unknown>) {
  const title = asString(
    thread.threadName ??
      thread.thread_name ??
      thread.name ??
      thread.title ??
      "",
  ).trim();
  return title || null;
}

function getSubagentTitleLanguage(parentTitle: string): SubagentTitleLanguage {
  const hasCjk = /[\u3400-\u9fff]/.test(parentTitle);
  const hasLatin = /[A-Za-z]/.test(parentTitle);
  if (hasCjk && hasLatin) {
    return "mixed";
  }
  return hasCjk ? "zh" : "en";
}

function buildSubagentTitlePrompt(
  parentTitle: string,
  taskTitle: string,
  language: SubagentTitleLanguage,
) {
  if (language === "zh") {
    return [
      `父会话标题：${parentTitle}`,
      `子任务标识：${taskTitle}`,
      "请生成简洁的中文子任务显示标题，并保留子任务语义。",
    ].join("\n");
  }
  if (language === "mixed") {
    return [
      `父会话标题 / Parent conversation title：${parentTitle}`,
      `子任务标识 / Subagent task identifier：${taskTitle}`,
      "标题必须跟随父会话标题的主要语言并保留子任务语义。The title must follow the parent conversation title's primary language and preserve the subagent task meaning.",
    ].join("\n");
  }
  return [
    `Parent conversation title: ${parentTitle}`,
    `Subagent task identifier: ${taskTitle}`,
    "Generate a concise English display title for the subagent task while preserving the task meaning.",
  ].join("\n");
}

function titleMatchesLanguage(title: string, language: SubagentTitleLanguage) {
  if (language === "mixed") {
    return true;
  }
  const hasCjk = /[\u3400-\u9fff]/.test(title);
  return language === "zh" ? hasCjk : !hasCjk;
}

function cleanPromptText(text: string) {
  if (!text) {
    return "";
  }
  const withoutImages = text.replace(/\[image(?: x\d+)?\]/gi, " ");
  const withoutSkills = withoutImages.replace(/(^|\s)\$[A-Za-z0-9_-]+(?=\s|$)/g, " ");
  const normalized = withoutSkills.replace(/\s+/g, " ").trim();
  return normalized.length > MAX_PROMPT_CHARS
    ? normalized.slice(0, MAX_PROMPT_CHARS)
    : normalized;
}

function isUserMessage(
  item: ConversationItem,
): item is Extract<ConversationItem, { kind: "message" }> {
  return item.kind === "message" && item.role === "user";
}

type UseThreadTitleAutogenerationOptions = {
  enabled: boolean;
  itemsByThreadRef: MutableRefObject<Record<string, ConversationItem[]>>;
  threadsByWorkspace: Record<string, ThreadSummary[]>;
  threadsByWorkspaceRef: MutableRefObject<Record<string, ThreadSummary[]>>;
  getCustomName: (workspaceId: string, threadId: string) => string | undefined;
  renameThread: (workspaceId: string, threadId: string, title: string) => void;
  persistGeneratedTitle: (
    workspaceId: string,
    threadId: string,
    title: string,
  ) => void;
  onDebug?: (entry: DebugEntry) => void;
};

export function useThreadTitleAutogeneration({
  enabled,
  itemsByThreadRef,
  threadsByWorkspace,
  threadsByWorkspaceRef,
  getCustomName,
  renameThread,
  persistGeneratedTitle,
  onDebug,
}: UseThreadTitleAutogenerationOptions) {
  const inFlightRef = useRef<Record<string, true>>({});
  const subagentInFlightRef = useRef<Record<string, true>>({});
  const subagentQueuedRef = useRef<Record<string, true>>({});
  const subagentQueueByWorkspaceRef = useRef<Record<string, Promise<void>>>({});
  const subagentAttemptsRef = useRef<Record<string, number>>({});
  const pendingSubagentTitlesRef = useRef<Record<string, SubagentTitleCandidate>>({});
  const subagentRetryTimersRef = useRef<
    Record<string, ReturnType<typeof setTimeout>>
  >({});
  const disposedRef = useRef(false);
  const enabledRef = useRef(enabled);
  enabledRef.current = enabled;

  const clearSubagentRetry = useCallback((key: string) => {
    const timer = subagentRetryTimersRef.current[key];
    if (timer !== undefined) {
      clearTimeout(timer);
      delete subagentRetryTimersRef.current[key];
    }
  }, []);

  const processSubagentTitleCandidate = useCallback(
    async (candidate: SubagentTitleCandidate) => {
      const { key, workspaceId, threadId, parentThreadId, taskTitle } = candidate;
      if (
        disposedRef.current ||
        !enabledRef.current ||
        subagentInFlightRef.current[key]
      ) {
        return;
      }
      if (getCustomName(workspaceId, threadId)) {
        delete pendingSubagentTitlesRef.current[key];
        clearSubagentRetry(key);
        return;
      }

      const threads = threadsByWorkspaceRef.current[workspaceId] ?? [];
      const parentThread = threads.find((thread) => thread.id === parentThreadId);
      const parentTitle = parentThread?.name.trim() ?? "";
      if (!parentTitle) {
        return;
      }
      const childThread = threads.find((thread) => thread.id === threadId);
      if (
        childThread &&
        childThread.name !== taskTitle &&
        !looksAutoGeneratedThreadName(childThread.name)
      ) {
        delete pendingSubagentTitlesRef.current[key];
        clearSubagentRetry(key);
        return;
      }

      const attempts = subagentAttemptsRef.current[key] ?? 0;
      if (attempts >= MAX_SUBAGENT_TITLE_ATTEMPTS) {
        delete pendingSubagentTitlesRef.current[key];
        clearSubagentRetry(key);
        return;
      }
      subagentAttemptsRef.current[key] = attempts + 1;
      subagentInFlightRef.current[key] = true;
      const language = getSubagentTitleLanguage(parentTitle);
      try {
        const metadata = await generateRunMetadata(
          workspaceId,
          buildSubagentTitlePrompt(parentTitle, taskTitle, language),
        );
        const title = clampThreadName(metadata.title ?? "");
        if (!title || !titleMatchesLanguage(title, language)) {
          throw new Error("Generated subagent title language did not match parent title");
        }
        if (
          disposedRef.current ||
          !enabledRef.current ||
          getCustomName(workspaceId, threadId)
        ) {
          delete pendingSubagentTitlesRef.current[key];
          clearSubagentRetry(key);
          return;
        }
        const latestThread = threadsByWorkspaceRef.current[workspaceId]?.find(
          (thread) => thread.id === threadId,
        );
        if (
          latestThread &&
          latestThread.name !== taskTitle &&
          !looksAutoGeneratedThreadName(latestThread.name)
        ) {
          delete pendingSubagentTitlesRef.current[key];
          clearSubagentRetry(key);
          return;
        }
        persistGeneratedTitle(workspaceId, threadId, title);
        delete pendingSubagentTitlesRef.current[key];
        clearSubagentRetry(key);
      } catch (error) {
        if (disposedRef.current) {
          return;
        }
        onDebug?.({
          id: `${Date.now()}-subagent-title-autogen-error`,
          timestamp: Date.now(),
          source: "error",
          label: "thread/subagent title autogen error",
          payload: {
            workspaceId,
            threadId,
            parentThreadId,
            attempt: subagentAttemptsRef.current[key],
            error: error instanceof Error ? error.message : String(error),
          },
        });
        if (subagentAttemptsRef.current[key] >= MAX_SUBAGENT_TITLE_ATTEMPTS) {
          delete pendingSubagentTitlesRef.current[key];
          clearSubagentRetry(key);
        } else if (subagentRetryTimersRef.current[key] === undefined) {
          subagentRetryTimersRef.current[key] = setTimeout(() => {
            delete subagentRetryTimersRef.current[key];
            if (disposedRef.current) {
              return;
            }
            const pending = pendingSubagentTitlesRef.current[key];
            if (pending) {
              void enqueueSubagentTitleCandidateRef.current(pending);
            }
          }, SUBAGENT_TITLE_RETRY_DELAY_MS);
        }
      } finally {
        delete subagentInFlightRef.current[key];
      }
    },
    [
      clearSubagentRetry,
      getCustomName,
      onDebug,
      persistGeneratedTitle,
      threadsByWorkspaceRef,
    ],
  );

  const enqueueSubagentTitleCandidateRef = useRef<
    (candidate: SubagentTitleCandidate) => Promise<void>
  >(async () => undefined);

  const enqueueSubagentTitleCandidate = useCallback(
    (candidate: SubagentTitleCandidate) => {
      const { key } = candidate;
      if (
        disposedRef.current ||
        subagentQueuedRef.current[key] ||
        subagentInFlightRef.current[key]
      ) {
        return Promise.resolve();
      }
      subagentQueuedRef.current[key] = true;
      const workspaceQueue =
        subagentQueueByWorkspaceRef.current[candidate.workspaceId] ?? Promise.resolve();
      const run = workspaceQueue.then(async () => {
        delete subagentQueuedRef.current[key];
        await processSubagentTitleCandidate(candidate);
      });
      subagentQueueByWorkspaceRef.current[candidate.workspaceId] = run.catch(
        () => undefined,
      );
      return run;
    },
    [processSubagentTitleCandidate],
  );
  enqueueSubagentTitleCandidateRef.current = enqueueSubagentTitleCandidate;

  const onSubagentThreadDetected = useCallback(
    async (workspaceId: string, thread: Record<string, unknown>) => {
      if (disposedRef.current || !enabled || !workspaceId) {
        return;
      }
      const threadId = asString(thread.id).trim();
      const parentThreadId = getParentThreadIdFromThread(thread);
      const taskTitle = getSubagentTaskTitleFromThread(thread);
      if (!threadId || !parentThreadId || !taskTitle) {
        return;
      }
      const formalTitle = getFormalThreadTitle(thread);
      if (formalTitle && !looksAutoGeneratedThreadName(formalTitle)) {
        return;
      }
      if (getCustomName(workspaceId, threadId)) {
        return;
      }
      const key = `${workspaceId}:${threadId}`;
      const candidate =
        pendingSubagentTitlesRef.current[key] ??
        {
          key,
          workspaceId,
          threadId,
          parentThreadId,
          taskTitle,
        };
      pendingSubagentTitlesRef.current[key] = candidate;
      await enqueueSubagentTitleCandidate(candidate);
    },
    [enabled, enqueueSubagentTitleCandidate, getCustomName],
  );

  useEffect(() => {
    Object.values(pendingSubagentTitlesRef.current).forEach((candidate) => {
      void enqueueSubagentTitleCandidate(candidate);
    });
  }, [enqueueSubagentTitleCandidate, threadsByWorkspace]);

  useEffect(
    () => {
      disposedRef.current = false;
      return () => {
        disposedRef.current = true;
        Object.values(subagentRetryTimersRef.current).forEach((timer) => {
          clearTimeout(timer);
        });
        subagentRetryTimersRef.current = {};
        pendingSubagentTitlesRef.current = {};
        subagentQueuedRef.current = {};
      };
    },
    [],
  );

  useEffect(() => {
    if (enabled) {
      return;
    }
    Object.keys(subagentRetryTimersRef.current).forEach(clearSubagentRetry);
    pendingSubagentTitlesRef.current = {};
  }, [clearSubagentRetry, enabled]);

  const onUserMessageCreated = useCallback(
    async (workspaceId: string, threadId: string, text: string) => {
      if (!enabled) {
        return;
      }
      if (!workspaceId || !threadId) {
        return;
      }
      if (getCustomName(workspaceId, threadId)) {
        return;
      }
      const key = `${workspaceId}:${threadId}`;
      if (inFlightRef.current[key]) {
        return;
      }

      const cleaned = cleanPromptText(text);
      const existingItems = itemsByThreadRef.current[threadId] ?? [];
      const existingUserMessages = existingItems.filter(isUserMessage);
      const hasPriorConversation =
        existingUserMessages.length > 1 ||
        existingItems.some((item) => item.kind === "message" && item.role === "assistant") ||
        existingUserMessages.some((item) => cleanPromptText(item.text) !== cleaned);
      if (hasPriorConversation) {
        return;
      }

      const threads = threadsByWorkspaceRef.current[workspaceId] ?? [];
      const thread = threads.find((entry) => entry.id === threadId) ?? null;
      if (!cleaned) {
        return;
      }

      const promptPreviewName = clampThreadName(cleaned);
      if (
        thread &&
        !looksAutoGeneratedThreadName(thread.name) &&
        thread.name !== promptPreviewName
      ) {
        return;
      }

      inFlightRef.current[key] = true;
      try {
        const metadata = await generateRunMetadata(workspaceId, cleaned);
        const title = clampThreadName(metadata.title ?? "");
        if (!title) {
          return;
        }
        if (disposedRef.current || !enabledRef.current) {
          return;
        }
        if (getCustomName(workspaceId, threadId)) {
          return;
        }
        const latestThread =
          threadsByWorkspaceRef.current[workspaceId]?.find(
            (entry) => entry.id === threadId,
          ) ?? null;
        if (
          latestThread &&
          !looksAutoGeneratedThreadName(latestThread.name) &&
          latestThread.name !== promptPreviewName
        ) {
          return;
        }
        renameThread(workspaceId, threadId, title);
      } catch (error) {
        onDebug?.({
          id: `${Date.now()}-thread-title-autogen-error`,
          timestamp: Date.now(),
          source: "error",
          label: "thread/title autogen error",
          payload: error instanceof Error ? error.message : String(error),
        });
      } finally {
        delete inFlightRef.current[key];
      }
    },
    [
      enabled,
      getCustomName,
      itemsByThreadRef,
      threadsByWorkspaceRef,
      renameThread,
      onDebug,
    ],
  );

  return { onUserMessageCreated, onSubagentThreadDetected };
}
